---
title: "Covid19 exposure locations in the ACT"
resource_files:
- data/last.csv
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=TRUE}
library(tidyverse)
library(ggmap)
library(leaflet)
library(plotly)
library(flexdashboard)
library(DT)
ltab <- read.csv("data/last.csv")

#latest dataset
tab3 <- ltab
# Aggregate method
labs <- paste(tab3$Place, tab3$Date,tab3$Arrival.Time, tab3$Departure.Time, sep="<br/>") 
cols <- rep(c("red", "yellow", "blue"), each=2)
sym <- rep(c(15,16),3)
m <- leaflet() %>% addTiles()
# 
m <- m %>% addCircles(lat=tab3$lat, lng=tab3$lon,popup = labs, radius=8,weight=8, fillOpacity = 1, fillColor = cols[as.numeric(factor(tab3$type))], color = cols[as.numeric(factor(tab3$type))], opacity = 1)

```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart A

```{r}

#checks 
m


```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
DT::datatable(tab3[,c("table", "Status","Suburb","Place","Date","Arrival.Time","Departure.Time")],
  rownames = FALSE, options = list(pageLength = 10, ausoHideNavigation=TRUE, 
  initComplete = JS(
        "function(settings, json) {",
        "$(this.api().table().header()).css({'font-size': '50%'});",

        "}")))  %>% DT::formatStyle(columns = 1:7, fontSize='70%')
```



```{r}
### Chart C
# names(tab3)
# glimpse(tab3)

# countSub <- as.data.frame(table(as.factor(tab3$Suburb)))
# names(countSub) <- c("Suburb", "Total Count")
# 
# 
# # ggplot(countSub) + 
# #   geom_point(aes(x = Var1, y = Freq, col = Status))
# 
# 
# locs <- select(tab3, lat, lon, Suburb)
# 
# plotdat1 <- left_join(countSub, tab3, by = "Suburb")
# 
# # length(unique(as.factor(tab3$Suburb)))
# tab4 <- tab3 %>%
#   group_by(Suburb) %>%
#     summarise(count = length(as.factor(Suburb)),
#               lat = mean(lat),
#               lon = mean(lon)) 
# 
# tab5 <- tab4 %>%
# group_by(count)%>%
#       arrange(desc = TRUE, .by_group = TRUE)
#               
#               # ,
# 
# # glimpse(tab4)
# # glimpse(plotdat1)
# #filter on location
# 
# ggplot(tab5) + 
#   geom_point(aes(x = Suburb, y = count), size = 3) + 
#   theme(axis.text.x = element_text(angle = 90))
```

